services:
  db:
    image: postgres:17
    shm_size: ${POSTGRES_SHM_SIZE:-128mb}
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main
  web:
    build: .
    env_file: .env
    command: gunicorn bookwyrm.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/images
      - exports_volume:/app/exports
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000"]
      interval: 15s
      timeout: 10s
      start_period: 120s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
      redis_activity:
        condition: service_started
    networks:
      - main
  redis_activity:
    image: redis:7.2.1
    command: redis-server --requirepass ${REDIS_ACTIVITY_PASSWORD} --appendonly yes --port ${REDIS_ACTIVITY_PORT}
    volumes:
      - redis_activity_data:/data
    env_file: .env
    networks:
      - main
    restart: on-failure
  redis_broker:
    image: redis:7.2.1
    command: redis-server --requirepass ${REDIS_BROKER_PASSWORD} --appendonly yes --port ${REDIS_BROKER_PORT}
    volumes:
      - redis_broker_data:/data
    env_file: .env
    networks:
      - main
    restart: on-failure
  celery_worker:
    env_file: .env
    build: .
    networks:
      - main
    command: celery -A celerywyrm worker -l info -Q high_priority,medium_priority,low_priority,streams,images,suggested_users,email,connectors,lists,inbox,imports,import_triggered,broadcast,misc
    healthcheck:
      test: celery -A celerywyrm status
      interval: 30s
      timeout: 15s
      start_period: 60s
      retries: 10
    volumes:
      - static_volume:/app/static
      - media_volume:/app/images
      - exports_volume:/app/exports
    depends_on:
      web:
        condition: service_healthy
      db:
        condition: service_healthy
      redis_broker:
        condition: service_started
    restart: on-failure
  celery_beat:
    env_file: .env
    build: .
    networks:
      - main
    command: celery -A celerywyrm beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    healthcheck:
      test: celery -A celerywyrm status
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 60s
    volumes:
      - static_volume:/app/static
      - media_volume:/app/images
      - exports_volume:/app/exports
    depends_on:
      celery_worker:
        condition: service_healthy
    restart: on-failure
volumes:
  pgdata:
  static_volume:
  media_volume:
  exports_volume:
  redis_broker_data:
  redis_activity_data:
networks:
  main:
